// Code generated by internal/tools/genabi; DO NOT EDIT.

#ifndef DFGO_ABI_GENERATED_H
#define DFGO_ABI_GENERATED_H

#define DFGO_FUNCTIONS(X) \
  X(int32_t, dfgo_abi_version, (void), (), return) \
  X(const char *, dfgo_datafusion_version, (void), (), return) \
  X(int, dfgo_database_open, (const char * dsn, dfgo_database ** out, dfgo_error ** err), (dsn, out, err), return) \
  X(void, dfgo_database_close, (dfgo_database * db), (db), ) \
  X(int, dfgo_connection_open_isolated, (dfgo_database * db, dfgo_connection ** out, dfgo_error ** err), (db, out, err), return) \
  X(int, dfgo_connection_open_shared, (dfgo_database * db, dfgo_connection ** out, dfgo_error ** err), (db, out, err), return) \
  X(void, dfgo_connection_close, (dfgo_connection * conn), (conn), ) \
  X(int, dfgo_connection_register_arrow_ipc, (dfgo_connection * conn, const char * name, const uint8_t * data, int64_t len, dfgo_error ** err), (conn, name, data, len, err), return) \
  X(int, dfgo_connection_register_arrow_stream, (dfgo_connection * conn, const char * name, struct ArrowArrayStream * stream, dfgo_error ** err), (conn, name, stream, err), return) \
  X(int, dfgo_connection_register_ffi_table_provider, (dfgo_connection * conn, const char * name, const void * provider, const char * provider_datafusion_version, dfgo_error ** err), (conn, name, provider, provider_datafusion_version, err), return) \
  X(int, dfgo_connection_deregister_table, (dfgo_connection * conn, const char * name, dfgo_error ** err), (conn, name, err), return) \
  X(int, dfgo_prepare, (dfgo_connection * conn, const char * query, dfgo_statement ** out, dfgo_error ** err), (conn, query, out, err), return) \
  X(void, dfgo_statement_close, (dfgo_statement * stmt), (stmt), ) \
  X(int64_t, dfgo_statement_num_params, (dfgo_statement * stmt), (stmt), return) \
  X(int, dfgo_statement_serializes, (dfgo_statement * stmt), (stmt), return) \
  X(int, dfgo_cancel_token_create, (dfgo_cancel_token ** out, dfgo_error ** err), (out, err), return) \
  X(void, dfgo_cancel_token_cancel, (dfgo_cancel_token * token), (token), ) \
  X(void, dfgo_cancel_token_close, (dfgo_cancel_token * token), (token), ) \
  X(int, dfgo_statement_execute_with_params, (dfgo_statement * stmt, const dfgo_parameter * params, int64_t params_len, dfgo_cancel_token * token, dfgo_result_stream ** out, dfgo_error ** err), (stmt, params, params_len, token, out, err), return) \
  X(int, dfgo_result_export_arrow_stream, (dfgo_result_stream * result, struct ArrowArrayStream * out, dfgo_error ** err), (result, out, err), return) \
  X(void, dfgo_result_cancel, (dfgo_result_stream * result), (result), ) \
  X(void, dfgo_result_close, (dfgo_result_stream * result), (result), ) \
  X(const char *, dfgo_error_message, (const dfgo_error * err), (err), return) \
  X(const char *, dfgo_error_kind, (const dfgo_error * err), (err), return) \
  X(void, dfgo_error_free, (dfgo_error * err), (err), )

#endif
