// Code generated by internal/tools/genabi; DO NOT EDIT.

// Signature assignments are compile-time checks against the C declarations.
#[rustfmt::skip]
const _: unsafe extern "C" fn() -> i32 = super::dfgo_abi_version;
#[rustfmt::skip]
const _: unsafe extern "C" fn() -> *const std::ffi::c_char = super::dfgo_datafusion_version;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*const std::ffi::c_char, *mut *mut super::dfgo_database, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_database_open;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_database) -> () = super::dfgo_database_close;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_database, *mut *mut super::dfgo_connection, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_connection_open_isolated;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_database, *mut *mut super::dfgo_connection, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_connection_open_shared;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_connection) -> () = super::dfgo_connection_close;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_connection, *const std::ffi::c_char, *const u8, i64, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_connection_register_arrow_ipc;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_connection, *const std::ffi::c_char, *mut datafusion::arrow::ffi_stream::FFI_ArrowArrayStream, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_connection_register_arrow_stream;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_connection, *const std::ffi::c_char, *const std::ffi::c_void, *const std::ffi::c_char, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_connection_register_ffi_table_provider;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_connection, *const std::ffi::c_char, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_connection_deregister_table;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_connection, *const std::ffi::c_char, *mut *mut super::dfgo_statement, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_prepare;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_statement) -> () = super::dfgo_statement_close;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_statement) -> i64 = super::dfgo_statement_num_params;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_statement) -> std::ffi::c_int = super::dfgo_statement_serializes;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut *mut super::dfgo_cancel_token, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_cancel_token_create;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_cancel_token) -> () = super::dfgo_cancel_token_cancel;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_cancel_token) -> () = super::dfgo_cancel_token_close;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_statement, *const super::dfgo_parameter, i64, *mut super::dfgo_cancel_token, *mut *mut super::dfgo_result_stream, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_statement_execute_with_params;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_result_stream, *mut datafusion::arrow::ffi_stream::FFI_ArrowArrayStream, *mut *mut super::dfgo_error) -> std::ffi::c_int = super::dfgo_result_export_arrow_stream;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_result_stream) -> () = super::dfgo_result_cancel;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_result_stream) -> () = super::dfgo_result_close;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*const super::dfgo_error) -> *const std::ffi::c_char = super::dfgo_error_message;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*const super::dfgo_error) -> *const std::ffi::c_char = super::dfgo_error_kind;
#[rustfmt::skip]
const _: unsafe extern "C" fn(*mut super::dfgo_error) -> () = super::dfgo_error_free;

const _: fn(&super::dfgo_parameter) = |p| {
    let _: i64 = p.index;
    let _: *const std::ffi::c_char = p.name;
    let _: i64 = p.name_len;
    let _: i32 = p.type_code;
    let _: i32 = p.is_null;
    let _: i64 = p.int64_value;
    let _: u64 = p.uint64_value;
    let _: f64 = p.float64_value;
    let _: *const u8 = p.data;
    let _: i64 = p.data_len;
    let _: *const std::ffi::c_char = p.timezone;
    let _: i64 = p.timezone_len;
    let _: u8 = p.precision;
    let _: i8 = p.scale;
};

#[rustfmt::skip]
pub(super) fn rust_layout() -> Vec<usize> {
    use std::mem::{align_of, offset_of, size_of};
    use super::dfgo_parameter;
    use datafusion::arrow::{ffi::{FFI_ArrowArray, FFI_ArrowSchema}, ffi_stream::FFI_ArrowArrayStream};
    vec![
        size_of::<dfgo_parameter>(), align_of::<dfgo_parameter>(),
        size_of::<FFI_ArrowSchema>(), align_of::<FFI_ArrowSchema>(),
        size_of::<FFI_ArrowArray>(), align_of::<FFI_ArrowArray>(),
        size_of::<FFI_ArrowArrayStream>(), align_of::<FFI_ArrowArrayStream>(),
        offset_of!(dfgo_parameter, index),
        offset_of!(dfgo_parameter, name),
        offset_of!(dfgo_parameter, name_len),
        offset_of!(dfgo_parameter, type_code),
        offset_of!(dfgo_parameter, is_null),
        offset_of!(dfgo_parameter, int64_value),
        offset_of!(dfgo_parameter, uint64_value),
        offset_of!(dfgo_parameter, float64_value),
        offset_of!(dfgo_parameter, data),
        offset_of!(dfgo_parameter, data_len),
        offset_of!(dfgo_parameter, timezone),
        offset_of!(dfgo_parameter, timezone_len),
        offset_of!(dfgo_parameter, precision),
        offset_of!(dfgo_parameter, scale),
    ]
}
