// Code generated by internal/tools/genabi; DO NOT EDIT.

#include <stddef.h>
#include <stdio.h>
#include "datafusion_go.h"

int main(void) {
  printf("%zu %zu ", sizeof(dfgo_parameter), _Alignof(dfgo_parameter));
  printf("%zu %zu ", sizeof(struct ArrowSchema), _Alignof(struct ArrowSchema));
  printf("%zu %zu ", sizeof(struct ArrowArray), _Alignof(struct ArrowArray));
  printf("%zu %zu ", sizeof(struct ArrowArrayStream), _Alignof(struct ArrowArrayStream));
  printf("%zu ", offsetof(dfgo_parameter, index));
  printf("%zu ", offsetof(dfgo_parameter, name));
  printf("%zu ", offsetof(dfgo_parameter, name_len));
  printf("%zu ", offsetof(dfgo_parameter, type_code));
  printf("%zu ", offsetof(dfgo_parameter, is_null));
  printf("%zu ", offsetof(dfgo_parameter, int64_value));
  printf("%zu ", offsetof(dfgo_parameter, uint64_value));
  printf("%zu ", offsetof(dfgo_parameter, float64_value));
  printf("%zu ", offsetof(dfgo_parameter, data));
  printf("%zu ", offsetof(dfgo_parameter, data_len));
  printf("%zu ", offsetof(dfgo_parameter, timezone));
  printf("%zu ", offsetof(dfgo_parameter, timezone_len));
  printf("%zu ", offsetof(dfgo_parameter, precision));
  printf("%zu ", offsetof(dfgo_parameter, scale));
  putchar('\n');
  return 0;
}
